require("plugins-setup")
require("core.options")	
require("core.keymaps")
require("core.colorscheme")
require("core.autocmd")
require("core.commands")

require("plugins.comment")
require("plugins.fzf")
require("plugins.vimux")
require("plugins.gutentags")
