#!/usr/bin/env bash

session_name="bound"

if tmux has-session -t=$session_name 2> /dev/null; then
  if [[ -z $TMUX ]]; then
    tmux attach-session -t $session_name
  else
    tmux switch-client -t $session_name
  fi
  exit 0
fi

root="$DEV_DIR/bound"

dir_backend="$root/backend"
dir_frontend="$root/admin"
dir_driver="$root/driver-mobile"
dir_customer="$root/customer-mobile"

win_backend="backend"
win_frontend="admin"
win_driver="driver-mobile"
win_customer="customer-mobile"

function make_splits() {
  tmux split-window -t $session_name:$1 -c $2 -v -p 25
  tmux split-window -t $session_name:$1 -c $2 -h
  tmux select-pane -t $session_name:$1.1
}

function create_window() {
  tmux new-window -t $session_name -n $1 -c $2 "nvim ."
  make_splits $1 $2
}

tmux new-session -s $session_name -c $dir_backend -n $win_backend -d "nvim ."

make_splits $win_backend $dir_backend

create_window $win_frontend $dir_frontend
create_window $win_driver $dir_driver
create_window $win_customer $dir_customer

tmux select-window -t $session_name:$win_backend

tmux attach-session -t $session_name
