#!/bin/sh

if [[ $(uname) == "Darwin" ]]; then
  nvim="/opt/homebrew/bin/nvim"
else
  nvim="/usr/local/bin/nvim"
fi

while true; do
    nvim "$@"
    if [ $? -ne 111 ]; then
        break
    fi
done
