#!/usr/bin/env bash

set -eo pipefail

if [[ $# -eq 1 ]]; then
    selected=$1
else
    if command -v mess 2> /dev/null; then
      selected=$({ tmux list-sessions -F "#S"; mess git "$DEV_DIR"; } | fzf)
    else
      selected=$({ tmux list-sessions -F "#S"; find "$DEV_DIR" -execdir test -d {}/.git \; -type d -mindepth 1 -maxdepth 4 -print -prune; } | fzf)
    fi
fi

if [[ -z $selected ]]; then
    echo "nothing selected"
    exit 0
fi

if [[ $selected == "." ]]; then
  selected=$(pwd)
fi
selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -s "$selected_name" -c "$selected" -d "$SHELL -lc 'direnv exec . nvim . +Git; exec $SHELL'"
    tmux split-window -t "$selected_name" -c "$selected" -vl 10
    tmux split-window -t "$selected_name" -c "$selected" -h
    tmux select-pane -t "$selected_name":1.1
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t "$selected_name"
else
  tmux switch-client -t "$selected_name"
fi
