#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$({ tmux list-sessions -F "#S"; find ~/dev -execdir test -d {}/.git \; -type d -mindepth 1 -maxdepth 3 -print -prune; } | fzf)
fi

if [[ -z $selected ]]; then
    echo "nothing selected"
    exit 0
fi

if [[ $selected == "." ]]; then
  selected=$0
fi
selected_name=$(basename "$selected")

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -s $selected_name -c $selected -d "nvim ."
    tmux split-window -t $selected_name -c $selected -v -p 25
    tmux split-window -t $selected_name -c $selected -h
    tmux select-pane -t $selected_name:1.1
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t $selected_name
else
  tmux switch-client -t $selected_name
fi
